version: '2.3'

services:
  jenkins:
    container_name: jenkins
    build: ./master
    image: jenkins_casc
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_casc/jenkins.yaml
    ports:
      - "8080:8080"
    volumes:
      - jenkins_master_home:/var/jenkins_home
  jenkins_slave_docker:
    container_name: jenkins_agent_docker
    build: ./agent
    image: jenkins_agent_docker
    init: true
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0xJ5n9MY0PFBR/aCHSb8JBQgbIUo0C/bPlaxM9v0uCT2CQJvNyrHUfJKaM9wJsdT7wdKBUIvhODdfoE7kc59j0WpO5TQ5Q2MeG7fpQAalM0ATwv/o7hCTvWev5gpJPSsIg9N/+VusO2R4V1H7LpZm65hHL/0lt9SmvtZzQBR+lt5IhrliEMZpo1UdNql/ueR6Em3mFW/tJvprBD445xTa0kxACGXdMI3nF2+SF49oXhTPjNFKSJilWDsoWzf9swyIf1vbH6zr3slMm7jUvOSCC3gGcqNrSG9Y3wkBzqUDe20CjbeAHMq490xlkGQeg9BAByTvn9uOU7ym3mMUnkKR
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_TLS_VERIFY=1
    restart: on-failure
    depends_on:
      - jenkins
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins_slave_docker_workdir:/home/jenkins:z
      - jenkins_slave_docker:/home/jenkins/.jenkins
  docker:
    container_name: docker
    networks:
      - harbor
    image: docker:dind
    command: ["--insecure-registry=proxy:8080"]
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins_slave_docker_workdir:/home/jenkins:z
    privileged: true
volumes:
  jenkins_master_home:
  jenkins_slave_docker:
  jenkins-docker-certs:
  jenkins_slave_docker_workdir:
